Fail the job if unchecked items exist

diff --git a/.github/workflows/check-checklist.yml b/.github/workflows/check-checklist.yml
--- a/.github/workflows/check-checklist.yml
+++ b/.github/workflows/check-checklist.yml
@@ -62,3 +62,9 @@ jobs:
             repo: context.repo.repo,
             body: `Not all items in the checklist have been checked👀\n\nPlease review the following unchecked items in the PR description:\n${uncheckedItems}`
           })
+
+    - name: Fail the job if not all items are checked
+      if: env.all_checked == 'false'
+      run: |
+        echo "Failing the job because not all items in the checklist have been checked."
+        exit 1
